# -*- coding: utf-8 -*-
# Tier reference (from RTE Robotics 2026-27 prospectus)
TIERS = {
    "BYTE": 200,
    "KILOBYTE": 500,
    "MEGABYTE": 1000,
    "GIGABYTE": 3000,
    "TERABYTE (Innovation Sponsor)": 5000,
    "PETABYTE (Title Sponsor)": 8000,
}

# Each row: (Company, Sector, Tier, Recommend line, Contact, Contact type, Source/Notes)
ROWS = [
# ---- AEROSPACE & DEFENSE (original) ----
("Boeing", "Aerospace & Defense", "TERABYTE (Innovation Sponsor)",
 "Boeing already runs active STEM community-engagement programmes in Qatar, so we recommend our Innovation Sponsor tier, which includes subsystem naming rights and a co-hosted STEM outreach event.",
 "evgeniia.teterina@boeing.com", "Verified - Boeing Middle East Communications",
 "Boeing does NOT accept unsolicited sponsorship requests by email - submit via the official form at boeing.com/company/key-orgs/brand/sponsorships first, then follow up with this contact. Source: boeing-me.com Qatar backgrounder."),
("Airbus", "Aerospace & Defense", "TERABYTE (Innovation Sponsor)",
 "As a leader in commercial aircraft manufacturing, Airbus is a strong fit for a partnership centred on our precision engineering and systems integration work.",
 "Search airbus.com contact / foundation pages", "Unverified - use website",
 "No public CSR email found in this pass; Airbus Foundation handles education partnerships."),
("NVIDIA", "Aerospace & Defense" , "GIGABYTE",
 "Given NVIDIA's leadership in AI and computing, we recommend spotlighting the machine learning and computer vision components of our robot's design.",
 "Search nvidia.com/en-us/about-nvidia/contact/", "Unverified - use website", ""),
("BAE Systems", "Aerospace & Defense", "GIGABYTE",
 "Given BAE Systems' focus on defense engineering, we recommend highlighting our robot's control systems and electronics design.",
 "Search baesystems.com contact / CSR pages", "Unverified - use website", ""),
("RTX", "Aerospace & Defense", "GIGABYTE",
 "As a leader in aerospace and defense technology, RTX is well matched to a partnership built around our systems engineering and sensor integration work.",
 "Search rtx.com/who-we-are/community", "Unverified - use website", ""),
("Rolls-Royce", "Aerospace & Defense", "GIGABYTE",
 "Given Rolls-Royce's engineering heritage in propulsion systems, we recommend a partnership emphasising our mechanical design and testing process.",
 "Search rolls-royce.com/sustainability", "Unverified - use website", ""),
("GE Aerospace", "Aerospace & Defense", "GIGABYTE",
 "As a leader in aircraft engine technology, GE Aerospace is a strong fit for a partnership highlighting our mechanical and systems engineering work.",
 "Search geaerospace.com/company/community", "Unverified - use website", ""),
("Lockheed Martin", "Aerospace & Defense", "GIGABYTE",
 "Given Lockheed Martin's work in advanced defense engineering, we recommend centring the partnership on our robotics control systems and problem-solving process.",
 "Search lockheedmartin.com/en-us/who-we-are/community.html", "Unverified - use website", ""),
("Thales", "Aerospace & Defense", "GIGABYTE",
 "As a company spanning aerospace, defense and digital identity, Thales is a strong match for a partnership highlighting both our hardware and software work.",
 "Search thalesgroup.com contact pages", "Unverified - use website", ""),
# ---- TECH & COMPUTING (original) ----
("Google", "Tech & Computing", "GIGABYTE",
 "As a leader in software and AI, Google is a natural fit for a partnership centred on our programming and computer science learning.",
 "Search google.com/about/community-engagement", "Unverified - use website", ""),
("Intel", "Tech & Computing", "GIGABYTE",
 "Given Intel's role in computing hardware, we recommend highlighting the embedded systems and electronics side of our build.",
 "Search intel.com/content/www/us/en/corporate-responsibility", "Unverified - use website", ""),
("Qualcomm", "Tech & Computing", "GIGABYTE",
 "Qualcomm has been a global FIRST sponsor since 2006 and presenting sponsor of past FIRST seasons - a partnership around our sensor and communications systems builds directly on that history.",
 "Search qualcomm.com/company/community", "Unverified - use website",
 "Verified: Qualcomm has sponsored FIRST globally since 2006 (Stock Titan / Qualcomm press release, Aug 2023)."),
("Cisco", "Tech & Computing", "MEGABYTE",
 "Given Cisco's focus on networking technology, we recommend highlighting the connectivity and control systems that let our robot communicate in real time.",
 "Search cisco.com/csr", "Unverified - use website", ""),
("HP", "Tech & Computing", "MEGABYTE",
 "As a computing hardware leader, HP is a strong fit for a partnership supporting the design and prototyping tools our team relies on.",
 "Search hp.com/us-en/hp-information/sustainable-impact.html", "Unverified - use website", ""),
("Dell Technologies", "Tech & Computing", "MEGABYTE",
 "Given Dell's role in computing infrastructure, we recommend supporting the technical tools and software our engineering process depends on.",
 "Search dell.com/en-us/dt/corporate/social-impact.htm", "Unverified - use website", ""),
("Microsoft Qatar", "Tech & Computing", "GIGABYTE",
 "As a leader in software and cloud technology, Microsoft Qatar is a strong match for a partnership centred on our programming and data tools.",
 "Search microsoft.com/en-qa/about", "Unverified - use website", ""),
# ---- INDUSTRIAL AUTOMATION (original) ----
("Siemens", "Industrial Automation", "MEGABYTE",
 "Siemens already runs a global FIRST Robotics sponsorship programme (free Solid Edge / PADS software plus $1,000 cash grants to eligible teams) - we recommend applying directly through that programme alongside a MEGABYTE-tier ask.",
 "Apply via solidedge.siemens.com/en/first-robotics/", "Verified - official FIRST sponsorship programme",
 "Verified: Siemens grants $1,000 to eligible FIRST teams and gives free Solid Edge/PADS software (solidedge.siemens.com)."),
("ABB", "Industrial Automation", "GIGABYTE",
 "As a global leader in robotics and automation, ABB is a natural fit for a partnership centred on our robot's design and control systems.",
 "Search global.abb/group/en/sustainability", "Unverified - use website", ""),
("Schneider Electric", "Industrial Automation", "GIGABYTE",
 "Given Schneider Electric's focus on energy management and automation, we recommend highlighting the electrical systems design in our build.",
 "Search se.com/ww/en/about-us/sustainability", "Unverified - use website", ""),
("Honeywell", "Industrial Automation", "GIGABYTE",
 "As a leader spanning aerospace and industrial automation, Honeywell is well matched to a partnership highlighting our sensor and control systems work.",
 "Search honeywell.com/us/en/company/corporate-social-responsibility", "Unverified - use website", ""),
("Bosch", "Industrial Automation", "MEGABYTE",
 "Given Bosch's engineering breadth across industrial and automotive technology, we recommend centring the partnership on our mechanical design and manufacturing process.",
 "Search bosch.com/stories/csr", "Unverified - use website", ""),
# ---- QATAR ENERGY (original) ----
("QatarEnergy", "Qatar Energy", "PETABYTE (Title Sponsor)",
 "As Qatar's flagship energy company, QatarEnergy is a natural anchor for our top-tier Title Sponsor partnership, directly supporting Qatar National Vision 2030's push to develop homegrown engineering talent.",
 "Use official Get In Touch contact form", "Unverified - no public CSR email",
 "QatarEnergy publishes only fraud-alert and marketing/customer-registration emails; no CSR/sponsorship email is public. Source: qatarenergy.qa/en/MarketingAndTrading/Pages/GetInTouch.aspx"),
("Qatar Airways", "Qatar National / Aviation", "TERABYTE (Innovation Sponsor)",
 "Qatar Airways runs a formal sponsorship programme with environmental and social responsibility as a stated focus area - a strong fit for an Innovation Sponsor partnership.",
 "Submit via qatarairways.com/en/sponsorship.html", "Verified - official sponsorship proposal form",
 "Verified: Qatar Airways requires proposals via its official form, submitted 12+ weeks before the event; no direct email accepted. Source: qatarairways.com/en/sponsorship.html"),
("ExxonMobil Qatar", "Qatar Energy", "TERABYTE (Innovation Sponsor)",
 "ExxonMobil Qatar just renewed its multi-year partnership with Teach For Qatar to advance education and STEM innovation - our season aligns directly with that renewed commitment.",
 "Search qatar.exxonmobil.com/community-engagement", "Unverified - use website",
 "Verified: ExxonMobil Qatar renewed its Teach For Qatar STEM/education partnership for 3 more years, April 2026. Source: thepeninsulaqatar.com."),
("Shell Qatar", "Qatar Energy", "GIGABYTE",
 "Given Shell's investment in Qatar's energy sector, we recommend centring the partnership on developing the local engineering talent pipeline.",
 "Search shell.com.qa or shell.com/sustainability", "Unverified - use website", ""),
# ---- QATAR NATIONAL / FOUNDATION (original) ----
("Qatar Foundation", "Qatar National / Education", "TERABYTE (Innovation Sponsor)",
 "As our team already operates under HBKU (a Qatar Foundation entity), we recommend formalising that existing relationship with an official Innovation Sponsor partnership.",
 "partnerships@qf.org.qa", "Verified - QF Partnerships team",
 "Verified official contact: qf.org.qa/about/partnerships (general: info@qf.org.qa)."),
# ---- QATAR TELECOM (original) ----
("Ooredoo Qatar", "Qatar Telecom", "GIGABYTE",
 "Ooredoo has a dedicated Director of CSR, Sponsorship & Media and a stated strategic commitment to CSR aligned with Qatar National Vision 2030 - a strong fit for our GIGABYTE tier.",
 "media@ooredoo.qa", "Verified - Media/CSR contact",
 "Verified via press releases on ooredoo.qa; also lists customer.service@ooredoo.qa for general enquiries."),
("Vodafone Qatar", "Qatar Telecom", "GIGABYTE",
 "Vodafone Qatar has a dedicated Head of Corporate Responsibility and an active 'Better World' CSR programme - a strong fit for our GIGABYTE tier.",
 "Mediarelations.qatar@vodafone.qa", "Verified - Media Relations",
 "Verified via vodafone.qa press releases (2024); CSR programme page at vodafone.qa/en/about-us/csr."),
# ---- QATAR BANKING (original) ----
("QNB", "Qatar Banking", "TERABYTE (Innovation Sponsor)",
 "QNB Group has an active community support programme sponsoring social, educational and sporting events, including past platinum-level education sponsorships - a strong fit for our Innovation Sponsor tier.",
 "PR@qnb.com", "Verified - Public Relations Department",
 "Verified via leadiq.com/QNB LinkedIn; QNB's PR dept handles community-support/CSR enquiries."),
("Commercial Bank Qatar", "Qatar Banking", "MEGABYTE",
 "Given Commercial Bank's community investment focus, we recommend a partnership framed around supporting STEM education in Qatar.",
 "Search cbq.qa/en/about-us/csr", "Unverified - use website", ""),
("QIB", "Qatar Banking", "MEGABYTE",
 "As a bank with a strong community presence in Qatar, QIB is a strong fit for a partnership centred on youth STEM development.",
 "Search qib.com.qa/en/about-us/corporate-social-responsibility", "Unverified - use website", ""),
("Doha Bank", "Qatar Banking", "MEGABYTE",
 "Doha Bank has publicly framed CSR as core to its corporate identity, with education and sustainability programming - a strong fit for a STEM-education partnership.",
 "Search dohabank.com.qa/en/about-us/csr", "Unverified - use website",
 "Doha Bank's CEO has spoken publicly about CSR being integral to the bank's identity (Gulf News interview)."),
# ---- QATAR IT / CONGLOMERATES (original) ----
("Meeza", "Qatar IT", "MEGABYTE",
 "As a Qatari IT and data services provider, we recommend highlighting the technical and programming side of our team's work.",
 "Search meeza.net/contact-us", "Unverified - use website", ""),
("Malomatia", "Qatar IT", "MEGABYTE",
 "Given Malomatia's focus on IT services in Qatar, we recommend centring the partnership on our team's software and systems engineering.",
 "Search malomatia.com/contact-us", "Unverified - use website", ""),
("Mannai Corporation", "Qatar Conglomerate", "GIGABYTE",
 "As a diversified Qatari conglomerate with an engineering and technology arm, Mannai is a strong fit for a partnership spanning both hardware and technical development.",
 "Search mannai.com.qa/contact", "Unverified - use website", ""),
# ---- QATAR MARITIME (original) ----
("Nakilat", "Qatar Maritime", "GIGABYTE",
 "As a leader in Qatar's maritime and LNG transport sector, we recommend framing the partnership around engineering talent development supporting Qatar's industrial base.",
 "Search nakilat.com/contact-us", "Unverified - use website", ""),
("Milaha", "Qatar Maritime", "MEGABYTE",
 "Given Milaha's role in Qatar's maritime and logistics sector, we recommend centring the partnership on the mechanical engineering side of our build.",
 "Search milaha.com/contact-us", "Unverified - use website", ""),
# ---- SUPPLIERS (original) ----
("GoMy3D", "Robotics/3D-Print Supplier", "KILOBYTE",
 "We'd welcome an in-kind partnership centred on print materials or equipment support alongside financial sponsorship.",
 "Search official GoMy3D website/store", "Unverified - use website", ""),
("Voltaat", "Power Tech Supplier (Qatar)", "KILOBYTE",
 "As a company focused on battery and power technology, Voltaat is a natural fit for a partnership centred on our robot's power systems.",
 "Search official Voltaat website", "Unverified - use website", ""),
("SMARTQAT", "Qatar Tech", "KILOBYTE",
 "Given SMARTQAT's technology focus in Qatar, we recommend centring the partnership on the technical and robotics side of our build.",
 "Search official SMARTQAT website", "Unverified - use website", ""),
("ACE Qatar", "Qatar Engineering Consultancy", "KILOBYTE",
 "Given ACE Qatar's engineering and technical consultancy focus, we recommend centring the partnership on our robot's design and build process.",
 "Search official ACE Qatar website", "Unverified - use website", ""),
("FK Tools", "Tools Supplier", "BYTE",
 "As a supplier of engineering tools, FK Tools is a strong fit for an in-kind partnership supporting our workshop equipment needs.",
 "Search official FK Tools website", "Unverified - use website", ""),
("Bambu Lab", "3D-Print Supplier", "KILOBYTE",
 "Our team already builds with a Bambu Lab H2D printer - we recommend formalising that relationship with an official sponsorship recognising your product's role in our build process.",
 "Search bambulab.com/en/support or partnerships", "Unverified - use website", ""),
("Sidra Medicine", "Qatar Healthcare/Research", "MEGABYTE",
 "As a research-driven institution, Sidra Medicine is a strong fit for a partnership highlighting the applied science and engineering side of our project.",
 "Search sidra.org/contact-us", "Unverified - use website", ""),

# ================= NEW ADDITIONS =================
# ---- Aerospace & Defense ----
("Northrop Grumman", "Aerospace & Defense (new)", "GIGABYTE",
 "As a leader in advanced defense and space systems, Northrop Grumman is a strong fit for a partnership highlighting our systems engineering and technical rigor.",
 "Search northropgrumman.com/community", "Unverified - use website", ""),
("L3Harris Technologies", "Aerospace & Defense (new)", "GIGABYTE",
 "Given L3Harris's focus on defense communications and sensor technology, we recommend a partnership centred on our robot's electronics and sensing systems.",
 "Search l3harris.com/our-company/corporate-citizenship", "Unverified - use website", ""),
("Leonardo", "Aerospace & Defense (new)", "GIGABYTE",
 "As a major aerospace, defense and security company, Leonardo is well matched to a partnership highlighting our engineering design process.",
 "Search leonardo.com/en/sustainability", "Unverified - use website", ""),
("Safran", "Aerospace & Defense (new)", "GIGABYTE",
 "Given Safran's focus on aerospace propulsion and equipment, we recommend a partnership centred on our mechanical design and testing work.",
 "Search safran-group.com/csr", "Unverified - use website", ""),
("Collins Aerospace", "Aerospace & Defense (new)", "MEGABYTE",
 "As an aerospace systems supplier, Collins Aerospace is a strong fit for a partnership highlighting our electronics and systems integration.",
 "Search collinsaerospace.com/who-we-are/sustainability", "Unverified - use website", ""),
("General Dynamics", "Aerospace & Defense (new)", "GIGABYTE",
 "Given General Dynamics' breadth across defense engineering, we recommend a partnership centred on our robot's technical development process.",
 "Search gd.com/corporate-citizenship", "Unverified - use website", ""),
("Embraer", "Aerospace & Defense (new)", "MEGABYTE",
 "As a commercial and defense aircraft manufacturer, Embraer is a strong fit for a partnership highlighting our aerospace-relevant engineering skills.",
 "Search embraer.com/global/en/sustainability", "Unverified - use website", ""),

# ---- Engineering software (robotics-relevant) ----
("Autodesk", "Engineering Software (new)", "MEGABYTE",
 "Autodesk already offers free education software licenses broadly - we recommend combining an in-kind software partnership with a MEGABYTE cash tier recognising your role in our CAD workflow.",
 "Search autodesk.com/education/edu-software/overview", "Unverified - use website", ""),
("Dassault Systemes (SOLIDWORKS)", "Engineering Software (new)", "MEGABYTE",
 "SOLIDWORKS is a long-time Crown Supplier of FIRST and already provides free SOLIDWORKS licenses to FIRST teams - we recommend formalising that relationship with an official MEGABYTE-tier local sponsorship.",
 "Apply via solidworks.com (FIRST Robotics programme) or a GoEngineer reseller", "Verified - official FIRST programme",
 "Verified: SOLIDWORKS/Dassault Systemes is a Crown Supplier of FIRST providing free CAD software to teams (goengineer.com)."),
("MathWorks", "Engineering Software (new)", "MEGABYTE",
 "Given MathWorks' MATLAB/Simulink tools are widely used in FIRST robotics programming, we recommend a partnership centred on our team's coding and control-systems education.",
 "Search mathworks.com/academia/highschool/first.html", "Unverified - use website", ""),
("National Instruments (NI)", "Engineering Software (new)", "MEGABYTE",
 "NI's long history supplying control hardware/software to FIRST teams makes this a natural fit for a partnership centred on our robot's control systems.",
 "Search ni.com/en/about-ni/corporate-social-responsibility.html", "Unverified - use website", ""),
("Amazon Web Services (AWS)", "Engineering Software (new)", "GIGABYTE",
 "As a leader in cloud computing, AWS is a strong fit for a partnership supporting the data and software infrastructure behind our robot's programming.",
 "Search aboutamazon.com/impact (AWS community/education)", "Unverified - use website", ""),
("IBM", "Engineering Software (new)", "GIGABYTE",
 "Given IBM's enterprise software and AI focus, we recommend a partnership highlighting the data and computing side of our engineering process.",
 "Search ibm.com/impact/education", "Unverified - use website", ""),
("Oracle", "Engineering Software (new)", "MEGABYTE",
 "As a global technology and database leader, Oracle is a strong fit for a partnership supporting our software and data-management education.",
 "Search oracle.com/corporate/citizenship", "Unverified - use website", ""),
("SAP", "Engineering Software (new)", "MEGABYTE",
 "Given SAP's enterprise software focus, we recommend a partnership highlighting our team's software engineering education.",
 "Search sap.com/about/company/sustainability.html", "Unverified - use website", ""),

# ---- Electronics / robotics suppliers ----
("Mouser Electronics", "Electronics Supplier (new)", "KILOBYTE",
 "Mouser has been a major FIRST sponsor since 2014, supporting teams with electronics components - a natural fit for an in-kind KILOBYTE partnership.",
 "See mouser.com/first/", "Verified - official FIRST sponsorship page",
 "Verified: Mouser Electronics has sponsored FIRST Robotics since 2014 (BusinessWire, March 2025)."),
("SparkFun Electronics", "Electronics Supplier (new)", "KILOBYTE",
 "As an open-source electronics supplier with a strong education focus, SparkFun is a good fit for an in-kind components partnership.",
 "Search sparkfun.com/categories/education", "Unverified - use website", ""),
("Adafruit Industries", "Electronics Supplier (new)", "KILOBYTE",
 "Given Adafruit's education-first approach to electronics, we recommend an in-kind components partnership supporting our build.",
 "Search adafruit.com/education", "Unverified - use website", ""),
("Festo", "Robotics/Automation Supplier (new)", "MEGABYTE",
 "As a global leader in automation and technical education (Festo Didactic), Festo is a strong fit for a partnership centred on our pneumatics and control systems.",
 "Search festo.com/us/en/e/about-festo/sustainability-id_453/", "Unverified - use website", ""),
("Formlabs", "3D-Print Supplier (new)", "KILOBYTE",
 "As a precision 3D printing company, Formlabs is a strong fit for an in-kind partnership supporting our rapid-prototyping workflow.",
 "Search formlabs.com/education", "Unverified - use website", ""),
("Ultimaker", "3D-Print Supplier (new)", "KILOBYTE",
 "Given Ultimaker's education focus, we recommend an in-kind 3D-printing partnership supporting our prototyping process.",
 "Search ultimaker.com/education", "Unverified - use website", ""),

# ---- Semiconductor / hardware ----
("Texas Instruments", "Semiconductor (new)", "MEGABYTE",
 "Given TI's role in embedded electronics, we recommend a partnership highlighting our robot's sensor and control-board design.",
 "Search ti.com/about-ti/corporate-citizenship/overview.html", "Unverified - use website", ""),
("STMicroelectronics", "Semiconductor (new)", "MEGABYTE",
 "As a global semiconductor leader, ST is a strong fit for a partnership centred on our robot's embedded electronics.",
 "Search st.com/content/st_com/en/about/sustainability.html", "Unverified - use website", ""),
("Huawei", "Tech Hardware (new)", "MEGABYTE",
 "Given Huawei's regional ICT investment and Seeds for the Future programme, we recommend a partnership centred on our team's technology education.",
 "Search huawei.com/en/sustainability", "Unverified - use website", ""),
("Samsung", "Tech Hardware (new)", "MEGABYTE",
 "As a global electronics leader active in STEM education (Samsung Solve for Tomorrow), Samsung is a strong fit for our education-focused partnership.",
 "Search samsung.com/global/sustainability", "Unverified - use website", ""),

# ---- Industrial automation, additional ----
("Emerson Electric", "Industrial Automation (new)", "GIGABYTE",
 "As a leader in automation and control technology (and NI's parent company), Emerson is a strong fit for a partnership centred on our control systems.",
 "Search emerson.com/en-us/about-us/corporate-social-responsibility", "Unverified - use website", ""),
("Rockwell Automation", "Industrial Automation (new)", "GIGABYTE",
 "Given Rockwell's leadership in industrial automation, we recommend a partnership highlighting our robot's control and automation systems.",
 "Search rockwellautomation.com/en-us/company/about-us/sustainability.html", "Unverified - use website", ""),
("Yokogawa", "Industrial Automation (new)", "MEGABYTE",
 "As a global industrial automation and instrumentation leader, Yokogawa is a good fit for a partnership centred on our sensor systems.",
 "Search yokogawa.com/csr", "Unverified - use website", ""),
("Mitsubishi Electric", "Industrial Automation (new)", "GIGABYTE",
 "Given Mitsubishi Electric's breadth in automation and electronics, we recommend a partnership highlighting our engineering design process.",
 "Search mitsubishielectric.com/en/sustainability", "Unverified - use website", ""),

# ---- Qatar Energy & Petrochemical, additional ----
("Qatar Petrochemical Company (QAPCO)", "Qatar Energy (new)", "MEGABYTE",
 "QAPCO's 2024 CSR report highlights active partnerships with QatarEnergy and the Al-Attiyah Foundation on education and community development - our season is a natural extension of that focus.",
 "Search qapco.com/en/sustainability", "Unverified - use website",
 "Verified from QAPCO's 2024 CSR Report (via ConocoPhillips-hosted PDF) referencing education/community-development partnerships."),
("Qatar Fuel (WOQOD)", "Qatar Energy (new)", "MEGABYTE",
 "As Qatar's national fuel distribution company, WOQOD is a strong fit for a partnership framed around supporting Qatar's future engineering workforce.",
 "Search woqod.com.qa/en/contact-us", "Unverified - use website", ""),
("Industries Qatar (IQ)", "Qatar Energy (new)", "GIGABYTE",
 "As the holding company for Qatar's major industrial manufacturers, Industries Qatar is a strong fit for a partnership centred on developing local engineering talent.",
 "Search iq.com.qa/en/contact-us", "Unverified - use website", ""),
("Qatargas", "Qatar Energy (new)", "GIGABYTE",
 "Given Qatargas's role in Qatar's LNG industry, we recommend framing the partnership around engineering workforce development.",
 "Search qatarenergylng.qa/english/contactus", "Unverified - use website", ""),

# ---- Qatar Banking, additional ----
("Al Rayan Bank", "Qatar Banking (new)", "MEGABYTE",
 "As a leading Islamic bank in Qatar, Al Rayan Bank is a strong fit for a partnership framed around community investment in STEM education.",
 "Search alrayan.com/en/about-us/csr", "Unverified - use website", ""),
("Dukhan Bank", "Qatar Banking (new)", "MEGABYTE",
 "Given Dukhan Bank's community investment focus, we recommend a partnership centred on developing Qatar's future engineers.",
 "Search dukhanbank.com/en/about-us", "Unverified - use website", ""),
("Qatar Development Bank", "Qatar Banking (new)", "MEGABYTE",
 "As a bank focused on developing Qatar's private sector and entrepreneurship, QDB is a strong fit for a partnership centred on future engineering talent.",
 "Search qdb.qa/en/contact-us", "Unverified - use website", ""),

# ---- Qatar Conglomerates / Holding ----
("Barwa Group", "Qatar Conglomerate (new)", "MEGABYTE",
 "As a major Qatari real estate and investment group, Barwa is a strong fit for a partnership framed around community and youth development.",
 "Search barwa.com.qa/en/contact-us", "Unverified - use website", ""),
("Power International Holding", "Qatar Conglomerate (new)", "MEGABYTE",
 "Given Power International Holding's diversified industrial interests, we recommend a partnership centred on engineering workforce development.",
 "Search official Power International Holding website", "Unverified - use website", ""),
("Al Faisal Holding", "Qatar Conglomerate (new)", "MEGABYTE",
 "As a diversified Qatari holding group, Al Faisal Holding is a strong fit for a community-investment partnership centred on STEM education.",
 "Search official Al Faisal Holding website", "Unverified - use website", ""),
("Estithmar Holding", "Qatar Conglomerate (new)", "MEGABYTE",
 "Given Estithmar Holding's engineering and construction interests, we recommend a partnership centred on our team's technical development.",
 "Search official Estithmar Holding website", "Unverified - use website", ""),
("Ezdan Holding Group", "Qatar Conglomerate (new)", "MEGABYTE",
 "As a major Qatari real estate group with a community investment focus, Ezdan Holding is a strong fit for a STEM-education partnership.",
 "Search ezdan.qa/en/contact-us", "Unverified - use website", ""),

# ---- Qatar Education / Foundation-linked ----
("WISE (Qatar Foundation)", "Qatar Education (new)", "MEGABYTE",
 "As Qatar Foundation's global education initiative, WISE is a strong fit for a partnership highlighting our team's innovation in STEM education.",
 "Search wise-qatar.org/contact", "Unverified - use website", ""),
("Education Above All", "Qatar Education (new)", "MEGABYTE",
 "Given Education Above All's global education mission, we recommend a partnership framed around expanding access to STEM learning.",
 "Search eaa.org.qa/en/contact-us", "Unverified - use website", ""),
("Reach Out To Asia (ROTA)", "Qatar Education (new)", "MEGABYTE",
 "As a Qatar Foundation education charity, ROTA is a strong fit for a partnership centred on youth STEM engagement.",
 "Search official ROTA / Qatar Foundation website", "Unverified - use website", ""),
("Al-Attiyah Foundation", "Qatar Education (new)", "MEGABYTE",
 "Given the Al-Attiyah Foundation's focus on energy and sustainable development education, it's a strong fit for a partnership centred on engineering-for-good.",
 "Search official Al-Attiyah Foundation website", "Unverified - use website",
 "Referenced as an active CSR/education partner in QAPCO's 2024 CSR report."),
("Silatech", "Qatar Education (new)", "MEGABYTE",
 "As an organisation focused on youth employment and entrepreneurship, Silatech is a strong fit for a partnership centred on developing future engineers.",
 "Search official Silatech website", "Unverified - use website", ""),
("Qatar Chamber of Commerce & Industry", "Qatar Education (new)", "MEGABYTE",
 "Qatar Chamber actively trains member companies on CSR best practice - a partnership with us would be a concrete example of that commitment in action.",
 "Search qatarchamber.com/contact-us", "Unverified - use website",
 "Verified: Qatar Chamber runs CSR training programmes for member companies (Gulf Times, July 2026)."),

# ---- Professional services / consulting ----
("Deloitte Middle East (Qatar)", "Professional Services (new)", "MEGABYTE",
 "Given Deloitte's corporate responsibility programming in the region, we recommend a partnership framed around STEM education and mentorship.",
 "Search deloitte.com/qa/en/about/social-impact.html", "Unverified - use website", ""),
("PwC Middle East (Qatar)", "Professional Services (new)", "MEGABYTE",
 "As a professional services firm with active community programmes, PwC is a strong fit for a partnership centred on youth STEM development.",
 "Search pwc.com/m1/en/about-us/corporate-responsibility.html", "Unverified - use website", ""),
("EY Qatar", "Professional Services (new)", "MEGABYTE",
 "Given EY's regional corporate responsibility focus, we recommend a partnership framed around building Qatar's future engineering talent.",
 "Search ey.com/en_qa/about-us/corporate-responsibility", "Unverified - use website", ""),
("KPMG Qatar", "Professional Services (new)", "MEGABYTE",
 "As a professional services firm with a community-investment mandate, KPMG is a strong fit for a STEM-education partnership.",
 "Search kpmg.com/qa/en/home/about/corporate-responsibility.html", "Unverified - use website", ""),
("McKinsey & Company (Doha)", "Professional Services (new)", "GIGABYTE",
 "Given McKinsey's regional presence and focus on youth economic opportunity, we recommend a partnership framed around engineering workforce development.",
 "Search mckinsey.com/about-us/social-responsibility", "Unverified - use website", ""),

# ---- Media (Qatar) ----
("Al Jazeera Media Network", "Qatar Media (new)", "MEGABYTE",
 "Rather than (or alongside) cash sponsorship, Al Jazeera could offer media coverage and production support for our season - a strong non-monetary complement to a MEGABYTE-tier partnership.",
 "Search aljazeera.net/contact", "Unverified - use website", ""),
("beIN Media Group", "Qatar Media (new)", "MEGABYTE",
 "As with Al Jazeera, beIN could offer media coverage/production value alongside or instead of cash sponsorship, a good complement to a MEGABYTE tier.",
 "Search bein.com/en/contact-us", "Unverified - use website", ""),

# ---- Qatar CSR-active local businesses (found via search) ----
("Al Abdulghani Motors", "Qatar Local Business (new)", "KILOBYTE",
 "Al Abdulghani Motors is publicly active in Qatar's CSR community (Qatar CSR Summit) - a strong local prospect for a KILOBYTE-tier community partnership.",
 "Search official Al Abdulghani Motors website", "Unverified - use website",
 "Verified: Al Abdulghani Motors described its CSR initiatives at the 2024 Qatar CSR Summit (Qatar Tribune)."),
("Baladi Express / Souq Al Baladi", "Qatar Local Business (new)", "BYTE",
 "Baladi Express has publicly stated its CSR strategy prioritises supporting university/student programmes - a natural entry point for a BYTE-tier partnership with our student-led team.",
 "Search official Baladi Express / Souq Al Baladi website", "Unverified - use website",
 "Verified: Baladi Express representative stated their CSR strategy prioritises university student programmes (Qatar Tribune, 2024)."),
]

print(f"Total rows: {len(ROWS)}")